AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple template for a function behind an API gateway, supported by a DynamoDB table

Globals:
  Function:
    Timeout: 100
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  CognitoTestUserEmail:
    Description: Email address of the created user
    Type: String
  ApiStageName:
    Default: staging
    Description: StageName of API Gateway deployment
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    DependsOn: UserPool
    Properties:
      StageName: !Ref ApiStageName
      Cors: "'*'" # very permissive CORS for now
      # Cors: "'www.example.com'"  # SAM will automatically add AllowMethods with a list of methods for this API
      # DefinitionBody: # Pull in an OpenApi definition from S3
      #   'Fn::Transform':
      #     Name: 'AWS::Include'
      #     # Replace "bucket" with your bucket name
      #     Parameters:
      #       Location: s3://bucket/swagger.yaml
      Auth:
        # Do not provide a DefaultAuthorizer - instead mark endpoints that require authorization
        # DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
     
  FunctionOneRoot:
    Type: AWS::Serverless::Function
    Properties:
      Description: A simple serverless function - returns ok.
      CodeUri: ./src/SampleFunctions/FunctionOne/
      Handler: FunctionOne::FunctionOne.HandlerRoot::Handle
      Runtime: dotnet6
      MemorySize: 1024
      Events:
        RootResourceNoAuth:
          Type: Api
          Properties:
            Path: /FunctionOne/noauth
            Method: get
            RestApiId: !Ref ApiGateway
        RootResource:
          Type: Api
          Properties:
            Path: /FunctionOne
            Method: get
            RestApiId: !Ref ApiGateway
            Auth: # optional per endpoint
              Authorizer: CognitoAuthorizer
              AuthorizationScopes: 
                - profile
                - aws.cognito.signin.user.admin

  FunctionOneNotes:
    Type: AWS::Serverless::Function
    Properties:
      Description: A simple serverless function - GET to count notes, POST to add a note.
      CodeUri: ./src/SampleFunctions/FunctionOne/
      Handler: FunctionOne::FunctionOne.HandlerNotes::Handle
      Runtime: dotnet6
      MemorySize: 1024
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesDbTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref NotesDbTable
      Events:
        NotesResourceNoAuth:
          Type: Api
          Properties:
            Path: /FunctionOne/notes/noauth
            Method: ANY
            RestApiId: !Ref ApiGateway
        NotesResource:
          Type: Api
          Properties:
            Path: /FunctionOne/notes
            Method: ANY
            RestApiId: !Ref ApiGateway
            Auth: # optional per endpoint
              Authorizer: CognitoAuthorizer
              AuthorizationScopes: 
                - profile
                - aws.cognito.signin.user.admin

  NotesDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${AWS::StackName}-notes
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MvpAppUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 60 # (minutes) default value.
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - aws.cognito.signin.user.admin
        - email
        - openid
        - profile
      CallbackURLs:
        - https://instantiator.dev/auth-redirect-pages/logged_in.html
      ClientName: !Sub ${AWS::StackName}-UserPoolClient
      EnableTokenRevocation: true # default value.
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      IdTokenValidity: 60 # (minutes) default value.
      LogoutURLs:
        - https://instantiator.dev/auth-redirect-pages/logged_out.html
      PreventUserExistenceErrors: ENABLED # default value.
      RefreshTokenValidity: 30 # (days) default value.
      SupportedIdentityProviders:
        - COGNITO
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !Ref UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Sub '${AWS::StackName}'

  UserPoolCustomisation:
    Type: AWS::Cognito::UserPoolUICustomizationAttachment
    Properties: 
      ClientId: !Ref UserPoolClient
      UserPoolId: !Ref UserPool

  UserPoolTestUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      Username: !Ref CognitoTestUserEmail
      UserPoolId: !Ref UserPool

Outputs:
  FunctionOneEndpoint:
    Description: API Gateway endpoint URL with auth
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/staging/FunctionOne"
  UserPoolId:
    Description: "ID of the Cognito User Pool"
    Value: !Ref UserPool
  CognitoClientId:
    Description: "ID of the Cognito User Pool Client"
    Value: !Ref UserPoolClient
  TestUserEmail:
    Description: "Email address associated with the test user"
    Value: !Ref CognitoTestUserEmail
  